substitutions:
  name: "wt32-sc01"
  friendly_name: "WT32-SC01"
  id_prefix: "wt32_sc01"

esphome:
  name: statistiikkanaytto
  friendly_name: statistiikkanaytto
  includes: 
    - statistiikkanaytto/myscreen.h

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yourkeyhere"

ota:
  password: "yourpasswordhere"

wifi:
  domain: .home.local
  fast_connect: false
  reboot_timeout: 15min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: false
  manual_ip:
    static_ip: 10.0.60.79
    gateway: 10.0.60.1
    subnet: 255.255.255.0
    dns1: 10.0.60.1
  ap:
    ssid: "Statistiikkanaytto"
    password: !secret fallback_hotspot

captive_portal:

external_components:
  - source: github://gpambrozio/esphome@FT6336U-touch
    components: [ ft63x6 ]

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_23_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_23_backlight_pwm
    name: "${friendly_name} Backlight"
    id: ${id_prefix}_backlight
    restore_mode: RESTORE_DEFAULT_ON
  
i2c:
  id: i2c_bus_intern
  sda: 18
  scl: 19
  scan: false

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

sensor:
  - platform: homeassistant
    id: espi_takkahuonelampotila
    entity_id: sensor.takkahuone_lampotila
  - platform: homeassistant
    id: espi_ulkolampotila
    entity_id: sensor.shelly_1_ilpinrele_external_temperature_0
  - platform: homeassistant
    id: espi_huonelampotila
    entity_id: sensor.l1_huonelampotila
  - platform: homeassistant
    id: espi_ollipc_gpuload
    entity_id: sensor.ollipc_gpuload
  - platform: homeassistant
    id: espi_ollipc_gputemperature
    entity_id: sensor.ollipc_gputemperature
  - platform: homeassistant
    id: espi_ollipc_memoryusage
    entity_id: sensor.ollipc_memoryusage



text_sensor:
  - platform: homeassistant
    id: kaytavanvalot
    entity_id: binary_sensor.kaytavanvalot
    internal: true
  - platform: homeassistant
    id: nayttovalot
    entity_id: binary_sensor.nayttovalot
    internal: true
  - platform: homeassistant
    id: takkahuoneen_valot
    entity_id: binary_sensor.takkahuoneen_valot
    internal: true
  - platform: homeassistant
    id: spotify_media_title
    entity_id: media_player.spotify_spotifyaccountname
    attribute: media_title
  - platform: homeassistant
    id: spotify_media_artist
    entity_id: media_player.spotify_spotifyaccountname
    attribute: media_artist
  - platform: homeassistant
    id: spotify
    entity_id: media_player.spotify_spotifyaccountname


display:
  - platform: ili9xxx
    id: ${id_prefix}_display
    model: ST7796
    cs_pin: GPIO15
    dc_pin: GPIO21
    reset_pin: GPIO22
    rotation: 90
    pages:
      - id: page1
        lambda: |-
          // Header
          it.printf(myscreen.settings.hxn,myscreen.settings.hyn, id(my_font), TextAlign::TOP_CENTER, "WT32-SC01");
          it.printf(myscreen.settings.hxv,myscreen.settings.hyv, id(my_font), TextAlign::TOP_CENTER, "Etusivu");
          // Content
          it.image(myscreen.settings.i1xi, myscreen.settings.i1yi, id(icon_home_termometer), id(my_red));
          it.printf(myscreen.settings.i1xv, myscreen.settings.i1yv, id(my_font_med), "%.1f °C", id(espi_takkahuonelampotila).state);
          it.image(myscreen.settings.i2xi, myscreen.settings.i1yi, id(icon_sun_termometer), id(my_blue));
          it.printf(myscreen.settings.i2xv, myscreen.settings.i1yv, id(my_font_med), "%.1f °C", id(espi_ulkolampotila).state);
          // Footer
          it.image(myscreen.settings.f1xi, myscreen.settings.f1yi, id(icon_previous_page));
          it.image(myscreen.settings.f2xi, myscreen.settings.f2yi, id(icon_next_page));
      - id: page2
        lambda: |-
          // Header
          it.printf(myscreen.settings.hxn,myscreen.settings.hyn, id(my_font), TextAlign::TOP_CENTER, "WT32-SC01");
          it.printf(myscreen.settings.hxv,myscreen.settings.hyv, id(my_font), TextAlign::TOP_CENTER, "Valot");
          // Text
          it.printf(64, 80, id(my_font_med), TextAlign::TOP_LEFT, "Kaytavan valot: ");
          it.printf(64, 140, id(my_font_med), TextAlign::TOP_LEFT, "Nayttovalot: ");
          it.printf(64, 200, id(my_font_med), TextAlign::TOP_LEFT, "Kattovalot: ");
          // Buttons
          if (id(kaytavanvalot).state == "on") {
              it.image(370, 68, id(icon_toggle_switch_on), id(my_green));
            } else if (id(kaytavanvalot).state == "off"){
                it.image(370, 68, id(icon_toggle_switch_off));
          }
          if (id(nayttovalot).state == "on") {
              it.image(370, 130, id(icon_toggle_switch_on), id(my_green));
            } else if (id(nayttovalot).state == "off"){
                it.image(370, 130, id(icon_toggle_switch_off));
          }
          if (id(takkahuoneen_valot).state == "on") {
              it.image(370, 192, id(icon_toggle_switch_on), id(my_green));
            } else if (id(takkahuoneen_valot).state == "off"){
                it.image(370, 192, id(icon_toggle_switch_off));
          }
          // Footer
          it.image(myscreen.settings.f1xi, myscreen.settings.f1yi, id(icon_previous_page));
          it.image(myscreen.settings.f2xi, myscreen.settings.f2yi, id(icon_next_page));
      - id: page3
        lambda: |-
          // Header
          it.printf(myscreen.settings.hxn,myscreen.settings.hyn, id(my_font), TextAlign::TOP_CENTER, "WT32-SC01");
          it.printf(myscreen.settings.hxv,myscreen.settings.hyv, id(my_font), TextAlign::TOP_CENTER, "Ollin PC");
          // Text
          it.printf(64, 80, id(my_font_med), TextAlign::TOP_LEFT, "GPU load: ");
          it.printf(64, 140, id(my_font_med), TextAlign::TOP_LEFT, "GPU temp: ");
          it.printf(64, 200, id(my_font_med), TextAlign::TOP_LEFT, "Mem usage: ");
          // Values
          it.printf(350, 80, id(my_font_med), "%.1f %%", id(espi_ollipc_gpuload).state);
          it.printf(350, 140, id(my_font_med), "%.1f °C", id(espi_ollipc_gputemperature).state);
          it.printf(350, 200, id(my_font_med), "%.1f %%", id(espi_ollipc_memoryusage).state);
          // Footer
          it.image(myscreen.settings.f1xi, myscreen.settings.f1yi, id(icon_previous_page));
          it.image(myscreen.settings.f2xi, myscreen.settings.f2yi, id(icon_next_page));
      - id: page4
        lambda: |-
          // Header
          it.printf(myscreen.settings.hxn,myscreen.settings.hyn, id(my_font), TextAlign::TOP_CENTER, "WT32-SC01");
          it.printf(myscreen.settings.hxv,myscreen.settings.hyv, id(my_font), TextAlign::TOP_CENTER, "Spotify");
          // Content
          if (id(spotify).state == "playing") {
            it.image(myscreen.settings.i1xi, myscreen.settings.i1yi, id(icon_music), id(my_green));
            it.image(myscreen.settings.i1r2xi, myscreen.settings.i1r2yi, id(icon_account_music), id(my_green));
            it.printf(myscreen.settings.i1xv, myscreen.settings.i1yv, id(my_font_min), "%s", id(spotify_media_title).state.c_str());
            it.printf(myscreen.settings.i1r2xv, myscreen.settings.i1r2yv, id(my_font_min), "%s", id(spotify_media_artist).state.c_str());
          } else if (id(spotify).state == "paused") {
              it.image(myscreen.settings.i1r2xi, myscreen.settings.i1r2yi, id(icon_speaker_paused), id(my_green));
              it.printf(myscreen.settings.i1r2xv, myscreen.settings.i1r2yv, id(my_font_min), "Spotify paused");
            }
              else if (id(spotify).state == "idle") {
                it.image(myscreen.settings.i1r2xi, myscreen.settings.i1r2yi, id(icon_speaker_off), id(my_green));
                it.printf(myscreen.settings.i1r2xv, myscreen.settings.i1r2yv, id(my_font_min), "Spotify turned off");
              }

          it.image(myscreen.settings.i1r3xi, myscreen.settings.i1r3yv, id(icon_music_previous), id(my_green));
          it.image(myscreen.settings.i2r3xi, myscreen.settings.i1r3yv, id(icon_music_play), id(my_green));
          it.image(myscreen.settings.i3r3xi, myscreen.settings.i1r3yv, id(icon_music_pause), id(my_green));
          it.image(myscreen.settings.i4r3xi, myscreen.settings.i1r3yv, id(icon_music_next), id(my_green));
          it.image(myscreen.settings.i1c4xi, myscreen.settings.i1c4yi, id(icon_music_volup), id(my_green));
          it.image(myscreen.settings.i2c4xi, myscreen.settings.i2c4yi, id(icon_music_voldown), id(my_green));
          // Footer
          it.image(myscreen.settings.f1xi, myscreen.settings.f1yi, id(icon_previous_page));
          it.image(myscreen.settings.f2xi, myscreen.settings.f2yi, id(icon_next_page));




image:
  - file: mdi:home-thermometer
    id: icon_home_termometer
    resize: 60x60
  - file: mdi:sun-thermometer
    id: icon_sun_termometer
    resize: 60x60
  - file: mdi:page-next-outline
    id: icon_next_page
    resize: 40x40
  - file: mdi:page-previous-outline
    id: icon_previous_page
    resize: 40x40
  - file: mdi:toggle-switch
    id: icon_toggle_switch_on
    resize: 80x80
  - file: mdi:toggle-switch-off-outline
    id: icon_toggle_switch_off
    resize: 80x80
  - file: mdi:music
    id: icon_music
    resize: 40x40
  - file: mdi:account-music
    id: icon_account_music
    resize: 40x40
  - file: mdi:speaker-pause
    id: icon_speaker_paused
    resize: 40x40
  - file: mdi:speaker-off
    id: icon_speaker_off
    resize: 40x40
  - file: mdi:skip-previous-circle-outline
    id: icon_music_previous
    resize: 80x80
  - file: mdi:skip-next-circle-outline
    id: icon_music_next
    resize: 80x80
  - file: mdi:play-circle-outline
    id: icon_music_play
    resize: 80x80
  - file: mdi:pause-circle-outline
    id: icon_music_pause
    resize: 80x80
  - file: mdi:plus-circle-outline
    id: icon_music_volup
    resize: 60x60
  - file: mdi:minus-circle-outline
    id: icon_music_voldown
    resize: 60x60





touchscreen:
  - platform: ft63x6
    id: ${id_prefix}_touch
    i2c_id: i2c_bus_intern
    on_touch:
      - logger.log:
          format: Touch at (%d, %d)
          args: [touch.x, touch.y]

font:
  - file:
      type: gfonts
      family: "Open Sans"
    id: my_font
    size: 20
  - file:
      type: gfonts
      family: "Open Sans"
    id: my_font_big
    size: 50
  - file:
      type: gfonts
      family: "Open Sans"
    id: my_font_med
    size: 35
  - file:
      type: gfonts
      family: "Open Sans"
    id: my_font_min
    size: 25


color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%

### "Page carousel" can possibly be achieved with this kind of config
#interval:
#  - interval: 8s
#    then:
#      - display.page.show_next: wt32_sc01_display
#      - component.update: wt32_sc01_display

binary_sensor:
  - platform: touchscreen
    name: Next
    id: next_view
    internal: True
    x_min: 420
    x_max: 460
    y_min: 280
    y_max: 320
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - display.page.show_next: wt32_sc01_display
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Previous
    id: previous_view
    internal: True
    x_min: 20
    x_max: 60
    y_min: 280
    y_max: 320
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - display.page.show_previous: wt32_sc01_display
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Kaytavanvalot
    id: touch_kaytavanvalot
    internal: True
    x_min: 365
    x_max: 470
    y_min: 68
    y_max: 108
    page_id: page2
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.shelly_1_kaytavanvalot_relay_0
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Nayttovalot
    id: touch_nayttovalot
    internal: True
    x_min: 365
    x_max: 470
    y_min: 140
    y_max: 188
    page_id: page2
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.ollin_nayttovalot
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Takkahuoneenvalot
    id: touch_takkahuoneenvalot
    internal: True
    x_min: 365
    x_max: 470
    y_min: 212
    y_max: 268
    page_id: page2
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.takkahuoneen_kattovalot
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Mediaprevious
    id: touch_mediaprevious
    internal: True
    x_min: 20
    x_max: 100
    y_min: 175
    y_max: 235
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: media_player.media_previous_track
            data:
              entity_id: media_player.spotify_spotifyaccountname
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Mediaplay
    id: touch_mediaplay
    internal: True
    x_min: 110
    x_max: 190
    y_min: 175
    y_max: 235
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: media_player.select_source
            data:
              source: OLLIPC
              entity_id: media_player.spotify_spotifyaccountname
        - homeassistant.service:
            service: media_player.media_play
            data:
              entity_id: media_player.spotify_spotifyaccountname
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Mediapause
    id: touch_mediapause
    internal: True
    x_min: 200
    x_max: 280
    y_min: 175
    y_max: 235
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: media_player.media_pause
            data:
              entity_id: media_player.spotify_spotifyaccountname
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Medianext
    id: touch_medianext
    internal: True
    x_min: 290
    x_max: 370
    y_min: 175
    y_max: 235
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: media_player.media_next_track
            data:
              entity_id: media_player.spotify_spotifyaccountname
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Mediavolup
    id: touch_mediavolup
    internal: True
    x_min: 395
    x_max: 455
    y_min: 130
    y_max: 190
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: button.press
            data:
              entity_id: button.ollipc_mediavolumeup
        - component.update: wt32_sc01_display

  - platform: touchscreen
    name: Mediavoldown
    id: touch_mediavoldown
    internal: True
    x_min: 395
    x_max: 455
    y_min: 195
    y_max: 255
    page_id: page4
    filters:
      - delayed_on: 300ms
    on_press:
      then:
        - homeassistant.service:
            service: button.press
            data:
              entity_id: button.ollipc_mediavolumedown
        - component.update: wt32_sc01_display
